algorithm: model
gpu_mode: True
gpus: [2]
threads: 4 #num_works

seed: 123 #123
data_dir_eval: /home/caizn/Awaresome-pansharpening/data/Data/WV2_data/test128

source_ms: ms
source_pan: pan

test:  #用于指标测试的代码
######################
  algorithm: model 
  datatype: GF2
  test_data: test128
  type: test 
######################
  data_dir: /home/caizn/Awaresome-pansharpening/data/Data/GF2_data/test128
  source_ms: ms
  source_pan: pan
  model: /home/caizn/best_model-epoch:13-psnr:30.0065-ergas:3.2850-sam:0.0803.ckpt
  save_dir: ./result/GF2/DIRFL/
  save_dir_rgb: ./result/GF2_rgb/DIRFL/
  test_config_path: ./configs/Train_DiCNN.json

test2:  #用于指标测试的代码
######################
  algorithm: model 
  datatype: WV2
  test_data: test128
  type: test 
######################
  data_dir: /home/caizn/Awaresome-pansharpening/data/Data/WV2_data/test128
  source_ms: ms
  source_pan: pan
  model: /home/caizn/best_model-epoch:13-psnr:30.0065-ergas:3.2850-sam:0.0803.ckpt
  save_dir: ./result/WV2/model/
  save_dir_rgb: ./result/WV2_rgb/model/
  test_config_path: ./configs/Train_DiCNN.json

test3:  #用于指标测试的代码
######################
  algorithm: model 
  datatype: WV3
  test_data: test128
  type: test
######################
  data_dir: /home/caizn/Awaresome-pansharpening/data/Data/WV3_data/test128
  source_ms: ms
  source_pan: pan
  model: /home/caizn/best_model-epoch:13-psnr:30.0065-ergas:3.2850-sam:0.0803.ckpt
  save_dir: ./result/WV3/model/
  save_dir_rgb: ./result/WV3_rgb/model/
  test_config_path: ./configs/Train_DiCNN.json

test4:  #用于指标测试的代码
######################
  algorithm: model 
  datatype: fullGF2
  test_data: test128
  type: test 
######################
  data_dir: /home/caizn/Awaresome-pansharpening/data/Data/fullGF2/test128
  source_ms: ms
  source_pan: pan
  model: /home/caizn/DIRFL/Experiments/models/GF2_dataset/EXP2/best_model-epoch:26-psnr:37.4859-ergas:1.3409-sam:0.0255.ckpt
  save_dir: ./result/WV3/DIRFL/
  save_dir_rgb: ./result/WV3_rgb/DIRFL/
  test_config_path: ./configs/Train_DiCNN.json

test5:  #用于指标测试的代码
######################
  algorithm: model 
  datatype: fullWV2
  test_data: test128
  type: test 
######################
  data_dir: /home/caizn/Awaresome-pansharpening/data/Data/fullWV2/test128
  source_ms: ms
  source_pan: pan
  model: /home/caizn/DIRFL/Experiments/models/wv2_dataset/EXP2/best_model-epoch:927-psnr:39.1370-ergas:1.2717-sam:0.0314.ckpt
  save_dir: ./result/WV3/DIRFL/
  save_dir_rgb: ./result/WV3_rgb/DIRFL/
  test_config_path: ./configs/Train_DiCNN.json

test6:  #用于指标测试的代码
######################
  algorithm: model 
  datatype: MSRS
  test_data: fullsize
  type: test
######################
  data_dir: /home1/caizn/IVF/MSRS-main/test
  source_vi: vi
  source_ir: ir
  source_fuse: fuse
  model: /home/caizn/DIRFL/Experiments/models/wv2_dataset/EXP2/best_model-epoch:927-psnr:39.1370-ergas:1.2717-sam:0.0314.ckpt
  save_dir: ./result/WV3/DIRFL/
  save_dir_rgb: ./result/WV3_rgb/DIRFL/
  test_config_path: ./configs/Train_DiCNN.json

data:
  upsacle:  4
  batch_size: 1 #4
  patch_size: 32
  data_augmentation: False
  n_colors: 4
  rgb_range: 255
  normalize : False
  
